// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ModernTenon.Api.Repositories.Implimentation;

#nullable disable

namespace ModernTenon.Api.Repositories.Implimentation.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20260401133952_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("ModernTenon.Api.Repositories.Contracts.Records.ProductRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<ulong?>("PriceInCents")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Products", t =>
                        {
                            t.HasCheckConstraint("CK_Products_Name_MinLength", "length(Name) >= 3");

                            t.HasCheckConstraint("CK_Products_PriceInCents_Positive", "\"PriceInCents\" IS NULL OR \"PriceInCents\" >= 1");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
